services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
    ports:
      - "11434:11434"
    dns:
      - "8.8.8.8"

volumes:
  ollama_models: